# Generated by Django 6.0.5 on 2026-05-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enclos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enclos', models.CharField(help_text='Ex : Étable Nord, Porcherie A', max_length=50)),
                ('type_enclos', models.CharField(choices=[('etable', 'Étable'), ('porcherie', 'Porcherie'), ('poulailler', 'Poulailler'), ('parc', 'Parc'), ('paddock', 'Paddock')], max_length=15)),
                ('capacite_max', models.PositiveIntegerField(help_text="Nombre maximum d'animaux")),
                ('superficie_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Enclos',
                'verbose_name_plural': 'Enclos',
                'db_table': 'enclos',
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_espece', models.CharField(help_text='Ex : Bovin, Porcin, Volaille', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Espèce',
                'db_table': 'espece',
            },
        ),
        migrations.CreateModel(
            name='StockProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(choices=[('lait', 'Lait'), ('viande', 'Viande'), ('oeuf', 'Œuf'), ('engrais_traite', 'Engrais traité')], max_length=15, unique=True)),
                ('quantite_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('unite', models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilogramme'), ('unite', 'Unité'), ('sac', 'Sac')], max_length=10)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Stock produit',
                'db_table': 'stock_produit',
            },
        ),
        migrations.CreateModel(
            name='TypeAliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : Herbe, Son de riz, Maïs, Eau', max_length=80, unique=True)),
                ('categorie', models.CharField(choices=[('fourrage', 'Fourrage'), ('concentre', 'Concentré'), ('mineraux', 'Minéraux'), ('eau', 'Eau'), ('complement', 'Complément')], max_length=15)),
                ('unite_mesure', models.CharField(choices=[('kg', 'Kilogramme'), ('litre', 'Litre'), ('botte', 'Botte'), ('sac', 'Sac')], max_length=10)),
                ('cout_unitaire_ariary', models.DecimalField(blank=True, decimal_places=2, help_text='Coût moyen en Ariary (MGA)', max_digits=8, null=True)),
                ('origine', models.CharField(blank=True, choices=[('produit_ferme', 'Produit dans la ferme'), ('achat_marche', 'Acheté au marché')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': "Type d'aliment",
                'db_table': 'type_aliment',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(choices=[('lait', 'Lait'), ('viande', 'Viande'), ('oeuf', 'Œuf'), ('engrais', 'Engrais'), ('animal_vivant', 'Animal vivant')], max_length=15)),
                ('quantite_vendue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unite', models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilogramme'), ('unite', 'Unité'), ('sac', 'Sac'), ('tete', 'Tête')], max_length=10)),
                ('prix_unitaire_ariary', models.DecimalField(decimal_places=2, help_text='Prix en Ariary (MGA)', max_digits=10)),
                ('date_vente', models.DateField()),
                ('acheteur', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vente',
                'db_table': 'vente',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom_complet', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gerant', 'Gérant'), ('employe', 'Employé')], default='employe', max_length=10)),
                ('telephone', models.CharField(blank=True, help_text='Numéro Telma / Airtel / Orange MG', max_length=15, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_identification', models.CharField(help_text='Matricule / numéro de boucle', max_length=30, unique=True)),
                ('nom_local', models.CharField(blank=True, help_text="Nom vernaculaire donné par l'éleveur", max_length=60, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_acquisition', models.DateField()),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('vendu', 'Vendu'), ('mort', 'Mort'), ('reforme', 'Réformé')], default='actif', max_length=10)),
                ('origine', models.CharField(choices=[('naissance_ferme', 'Naissance dans la ferme'), ('achat', 'Achat'), ('don', 'Don')], max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('enclos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaux', to='ferme.enclos')),
            ],
            options={
                'verbose_name': 'Animal',
                'db_table': 'animal',
            },
        ),
        migrations.CreateModel(
            name='Engrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_engrais', models.CharField(choices=[('fumier_bovin', 'Fumier bovin'), ('fumier_porcin', 'Fumier porcin'), ('fiente_volaille', 'Fiente de volaille'), ('compost', 'Compost')], max_length=20)),
                ('date_collecte', models.DateField()),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut_traitement', models.CharField(choices=[('brut', 'Brut'), ('en_compostage', 'En compostage'), ('traite', 'Traité'), ('vendu', 'Vendu')], default='brut', max_length=15)),
                ('date_disponibilite', models.DateField(blank=True, help_text='Date prévue fin de compostage', null=True)),
                ('enclos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engrais', to='ferme.enclos')),
            ],
            options={
                'verbose_name': 'Engrais',
                'verbose_name_plural': 'Engrais',
                'db_table': 'engrais',
                'ordering': ['-date_collecte'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(choices=[('lait', 'Lait'), ('viande', 'Viande'), ('oeuf', 'Œuf'), ('fumier_brut', 'Fumier brut')], max_length=15)),
                ('date_collecte', models.DateField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unite', models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilogramme'), ('unite', 'Unité')], max_length=10)),
                ('qualite', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='ferme.animal')),
                ('enclos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='ferme.enclos')),
            ],
            options={
                'verbose_name': 'Production',
                'db_table': 'production',
                'ordering': ['-date_collecte'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_race', models.CharField(help_text='Ex : Zébu malgache, Large White, Rhode Island', max_length=80)),
                ('aptitude', models.CharField(choices=[('lait', 'Lait'), ('viande', 'Viande'), ('mixte', 'Mixte'), ('ponte', 'Ponte'), ('chair', 'Chair'), ('engrais', 'Engrais')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='races', to='ferme.espece')),
            ],
            options={
                'verbose_name': 'Race',
                'db_table': 'race',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='animaux', to='ferme.race'),
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saillie', models.DateField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nb_naissances', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nb_survivants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naissances_mere', to='ferme.animal')),
                ('pere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naissances_pere', to='ferme.animal')),
            ],
            options={
                'verbose_name': 'Reproduction',
                'db_table': 'reproduction',
                'ordering': ['-date_naissance'],
            },
        ),
        migrations.CreateModel(
            name='SanteAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evenement', models.DateField()),
                ('type_acte', models.CharField(choices=[('vaccination', 'Vaccination'), ('traitement', 'Traitement'), ('vermifuge', 'Vermifuge'), ('pesee', 'Pesée'), ('controle', 'Contrôle')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('medicament_utilise', models.CharField(blank=True, max_length=100, null=True)),
                ('cout_ariary', models.DecimalField(blank=True, decimal_places=2, help_text='Coût en MGA', max_digits=10, null=True)),
                ('veterinaire', models.CharField(blank=True, max_length=80, null=True)),
                ('prochain_rdv', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='ferme.animal')),
            ],
            options={
                'verbose_name': 'Acte vétérinaire',
                'db_table': 'sante_animal',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='StockAliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('type_aliment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='stock', to='ferme.typealiment')),
            ],
            options={
                'verbose_name': 'Stock aliment',
                'db_table': 'stock_aliment',
            },
        ),
        migrations.CreateModel(
            name='AlimentationAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_distribution', models.DateTimeField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('litre', 'Litre'), ('botte', 'Botte')], max_length=10)),
                ('responsable', models.CharField(blank=True, help_text="Nom de l'employé ou éleveur", max_length=80, null=True)),
                ('animal', models.ForeignKey(blank=True, help_text='Ration individuelle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentations', to='ferme.animal')),
                ('enclos', models.ForeignKey(blank=True, help_text='Ration groupée par enclos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentations', to='ferme.enclos')),
                ('type_aliment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='distributions', to='ferme.typealiment')),
            ],
            options={
                'verbose_name': 'Distribution alimentaire',
                'db_table': 'alimentation_animal',
                'ordering': ['-date_distribution'],
            },
        ),
    ]
